apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-config
  namespace: {{ .Values.namespace }}
  labels:
    app: adot-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    exporters:
      awsxray:
        region: {{ .Values.config.exporters.awsxray.region }}
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [awsxray]
