# https://taskfile.dev/
version: '3'

tasks:
  # Default task - shows available commands
  default:
    desc: List all available tasks
    cmds:
      - task --list

  # Formatting tasks
  format:
    desc: Format all Python code with Ruff
    cmds:
      - ruff format .

  format:check:
    desc: Check if code is formatted correctly
    cmds:
      - ruff format --check .

  # Linting tasks
  lint:
    desc: Run Ruff linter (read-only check)
    cmds:
      - ruff check .

  lint:fix:
    desc: Run Ruff linter and auto-fix issues
    cmds:
      - ruff check --fix .

  # Combined tasks
  check:
    desc: Run all checks (format + lint)
    cmds:
      - task: format:check
      - task: lint

  fix:
    desc: Format and fix all issues
    cmds:
      - task: format
      - task: lint:fix

  # Development server
  dev:
    desc: Start FastAPI development server
    cmds:
      - uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  # Testing (if you have tests)
  test:
    desc: Run all tests
    cmds:
      - pytest

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - pytest --cov=app --cov-report=html --cov-report=term

  # Database migrations (if using Alembic)
  db:migrate:
    desc: Run database migrations
    cmds:
      - alembic upgrade head

  db:rollback:
    desc: Rollback last migration
    cmds:
      - alembic downgrade -1

  # Clean up
  clean:
    desc: Remove cache and temporary files
    cmds:
      - rm -rf __pycache__
      - rm -rf .pytest_cache
      - rm -rf .ruff_cache
      - rm -rf .mypy_cache
      - rm -rf htmlcov
      - find . -type d -name "*.egg-info" -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete