{{- if eq .Values.global.namespace "aws" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.global.elasticache.primaryEndpoint }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      protocol: TCP
{{- end }}