import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthUserProvider } from '@/contexts/userContext';
import { Toaster } from 'sonner'




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
              <AuthUserProvider> 
          {/* // <UserDataProvider> */}
          {children}
          <Toaster
            position="top-right"
          expand={false}              // Set to true if you want toasts to expand on hover
          visibleToasts={4}           // Number of visible toasts (default is 3)
          closeButton={false}         // Show/hide close button
          richColors={false}          // Enable rich colors for different toast types
          theme="light"  
          />
        </AuthUserProvider>
        {/* // </UserDataProvider> */}

      </body>
    </html>
  );
}
