apiVersion: v2
name: adot-collector
description: AWS OpenTelemetry Collector for distributed tracing (X-Ray)
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: opentelemetry-collector
    version: "0.88.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: adotCollector.enabled
