"""added the family table and added it relationship to the users and tasks tables

Revision ID: eed5182623ef
Revises: 4d30f135c2a6
Create Date: 2025-07-18 20:28:06.455518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed5182623ef'
down_revision: Union[str, Sequence[str], None] = '4d30f135c2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.add_column('tasks', sa.Column('family_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'families', ['family_id'], ['id'])
    op.add_column('users', sa.Column('family_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'families', ['family_id'], ['id'])
    op.drop_column('users', 'family_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'family_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'family_id')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
