from datetime import datetime, date
from typing import Optional, List,Literal
from pydantic import BaseModel, ConfigDict, EmailStr

# User schemas
class UserBase(BaseModel):
    username: str
    email: EmailStr
    full_name: Optional[str] = None
    is_active: bool = True

class FamilyUsers(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int  # Added the missing id field
    username: str

class UserCreate(UserBase):
    password: str

class UserRequest(BaseModel):
    user_email: str
    
class FamilyRequest(BaseModel):
    family_id: int
    
class UserUpdate(BaseModel):
    username: Optional[str] = None
    email: Optional[EmailStr] = None
    full_name: Optional[str] = None
    is_active: Optional[bool] = None

class FamilyResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    name: str

class FamilyUsers(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    name: str
    users: List[FamilyUsers]




    

class UserResponse(UserBase):
    model_config = ConfigDict(from_attributes=True)
    
    id: int
    created_at: datetime
    updated_at: datetime
    family: Optional[FamilyResponse] 



class ChecklistItem(BaseModel):
    id: int  # this is autogenerated by the DB, so in input models it might be optional
    title: str
    completed: bool

# Task schemas
class TaskBase(BaseModel):
    title: str
    creator_id: int
    assignee_id: int
    family_id: int
    due_date: datetime
    status: Literal['initialised', 'in-progress', 'completed']
    checklist: Optional[List[ChecklistItem]]= None

# class TaskCreate(TaskBase):
#     pass

class TaskCreate(BaseModel):
    title: str | int
    creator_id: int
    assignee_id: int
    family_id: int
    due_date: datetime
    description: str
    status: Literal['initialised', 'in-progress', 'completed']
    checklist: Optional[List[ChecklistItem]]= None
class DeleteTask(TaskBase):
    task_id: str
class GetTasks(BaseModel):
    family_id: int
    date: date
class TaskUpdate(BaseModel):
    title: Optional[str] = None
    content: Optional[str] = None
    published: Optional[bool] = None

class TaskResponse(TaskBase):
    model_config = ConfigDict(from_attributes=True)
    
    id: int
    creator_id: int  
    created_at: datetime
    updated_at: datetime
    creator: UserResponse  




class LoginRequest(BaseModel):
    email: EmailStr
    password: str

class SignupRequest(BaseModel):
    email: EmailStr
    password: str
    name: str
    family_name: str

class EmailVerificationRequest(BaseModel):
    user_id: str
    

class ChecklistItem(BaseModel):
    id: str
    title: str
    completed: bool = False

    
class TaskRequest(BaseModel):
    id: str