{{- if eq .Values.namespace "aws" }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
    app: redis-external
spec:
  type: ExternalName
  externalName: {{ .Values.redis.host }}
  ports:
    - name: redis
      port: 6379
      protocol: TCP
{{- end }}